### ISSUE TITLE
"Ctrl-F" Find box doesn't do anything

### ISSUE THREAD

**Issue by thecodenation-ig** [rohankishore/Aura-Text#19]
The finder box that appears when we click Ctrl-F doesn't do anything. I tried hitting Enter and stuff, but to no avail. I updated to v1.5 and got this bug. Was fine until v1.2. Fix needed ASAP!!

**Comment by rohankishore** [comment]
Hi. This issue has been fixed in the new v1.6 update that was released few hours ago. I've also updated all the code files too. The issue should be resolved now. Happy editing!

Thanks for showing interest in Aura Text.
