### ISSUE TITLE
[Feature Request] Default app support

### ISSUE THREAD

**Issue by nfoert** [rohankishore/Aura-Text#23]
You should add the ability to set Aura Text as the default app for files.
I actually wanted to see how this worked myself, so I did some experimentation. It turns out that the file to open is in `sys.argv` like this:
`['C:\\path\\to\\executable.exe', 'C:\\path\\to\\file.py']` (On Windows)
So, the location of this file would be `sys.argv[1]`

Thanks for making Aura Text!

**Comment by rohankishore** [comment]
Hi nfoert. Can you elaborate more on the issue please? If you are comfortable, then we can talk on Discord, or on Instagram. Both of the social links are there in my profile bio. If you aren't comfortable, then we can just continue the discussion here.

Thanks for showing interest and using Aura Text.

**Comment by nfoert** [comment]
Sorry, I wasn't more clear. This isn't a bug report, It's a feature request. My apologies.

**Comment by rohankishore** [comment]
Yeah will surely try to integrate default behaviour more. As for now, you can:

`right click on a file  -->  Open with  -->  Choose another app  -->  Aura Text  --> Click on 'Always'`

The selected file format will now open default in Aura Text.

**Comment by rohankishore** [comment]
# Alternate but little more difficult way

![image](https://user-images.githubusercontent.com/109947257/224078221-184f6386-5d4b-4add-8727-70212fe6730e.png)

**Comment by nfoert** [comment]
Thank you. I tried both ways and they both cause Aura Text to throw a tkinter exception. `bitmap "icon.ico" not defined`
Because of this I figured it was not implemented.

Here's the full exception:
`Traceback (most recent call last):`
  `File "Aura Text.py", line 373, in <module>`
  `File "Aura Text.py", line 370, in main`
  `File "Aura Text.py", line 43, in __init__`
  `File "tkinter\__init__.py", line 2109, in wm_iconbitmap`
`_tkinter.TclError: bitmap "icon.ico" not defined`

**Comment by rohankishore** [comment]
Ok this has been noted and will be fixed asap (mostly today or within 2 days). Thanks for reporting.

**Comment by nfoert** [comment]
No problem.

**Comment by rohankishore** [comment]
Hi nfoert! I know it's been some time lol. We're actively trying to solve bugs and make Aura Text better.

In the latest version (v2.0), you can set Aura Text the default app for text formats without any errors. But the actual problem is, it doesn't read the file data. I'm still trying my best to solve this issue. 

In the meantime, try out the latest version. It features a whole new UI with better smoothness and also some animations with a splash screen!


Thanks,
Rohan

**Comment by nfoert** [comment]
No worries! The new splash screen, icons and UI look great.
