### ISSUE TITLE
Missing image assets

### ISSUE THREAD

**Issue by Paradoxdruid** [rohankishore/Aura-Text#4]
The github repo is missing a few referenced image assets needed to try out this code:

https://github.com/rohankishore/Aura-Notes/blob/13bace39cd0543e53765a5116c49141d0511516a/main.py#L40

https://github.com/rohankishore/Aura-Notes/blob/13bace39cd0543e53765a5116c49141d0511516a/main.py#L41

**Comment by rohankishore** [comment]
Yeah Sorry for that! The repo has been updated! Thanks for trying Aura Notes!

**Comment by Paradoxdruid** [comment]
Great!  Program runs now; I'll check it out.

**Comment by rohankishore** [comment]
Hi @Paradoxdruid. How was your experience with Aura Notes? I see you're using v1.0.6.. 

1.0.7 is out now with more fluid design and better and consistent color science.

Thanks for trying Aura Notes
