### ISSUE TITLE
Better linux support

### ISSUE THREAD

**Issue by scottpeterman** [rohankishore/Aura-Text#59]
So I tried running this on linux - you have pathing issues. obviously had to remove some windows/win32 type libraries, but it will run. I changed some path references to this: 
app_data_dir = os.path.realpath(os.path.join("LocalAppData"))
local_app_data = os.path.join(app_data_dir, "AuraText")

While considering if you want it to run on linux,  there are some improvements you could make to your terminal. I've done some work in that area you are welcome to re-use. https://github.com/scottpeterman/UglyWidgets
Works with cmd.exe, powershell or wsl.exe: 
import sys
from PyQt6.QtWidgets import QApplication, QMainWindow
from qtwincon_widget import Ui_Terminal

def main():
    app = QApplication(sys.argv)

    # Create a QMainWindow instance
    main_window = QMainWindow()
    main_window.resize(800, 600)  # Resize the window to 800x600

    # Create a Ui_Terminal instance
    shell = "cmd.exe"  # You can also use "powershell.exe" or "wsl.exe"
    terminal = Ui_Terminal(shell, main_window)

    # Set terminal as the central widget of main_window
    main_window.setCentralWidget(terminal)
    main_window.setWindowTitle(f"PyQt6 - Terminal Widget - Shell is: {shell}")

    main_window.show()

    sys.exit(app.exec())

if __name__ == "__main__":
    main()

**Comment by rohankishore** [comment]
Hey @scottpeterman!

Thank you for your contribution. I'd consider using your Terminal widget.

**Comment by rohankishore** [comment]
I've credit you too thanks a lot for the widgets ;)

**Comment by scottpeterman** [comment]
Thanks very much!
