### ISSUE TITLE
[BUG] Cannot import name 'get_started' from 'auratext.Core'

### ISSUE THREAD

**Issue by johnstanforth** [rohankishore/Aura-Text#66]
# Bug

After trying to run Aura Text on Ubuntu/Linux, I think it probably only runs on Windows, given the win32 python modules used?  You should probably add a bold/highlighted note in the README explaining that.  But regardless, I think the bug below would exist on Windows too, so I'm creating the Issue here just in case it's helpful to you and others.

When trying to start Aura Text with ```python -m main```, it exits with an import error for a missing ```get_started``` module.  And the codebase doesn't contain it; its only use (in ```window.py``` line 82) was commented out, replaced with just an empty ```pass``` in the previous line (81).  Probably just need to remove the ```import``` lines?

```
main.py
10:from auratext.Core import get_started

auratext/Core/window.py
31:from . import get_started
82:                # get_started.show_setup_window()
```

<br>

## Screenshot / Traceback Output

```
% python -m main
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "[...]/Aura-Text/main.py", line 9, in <module>
    from auratext.Core.window import Window
  File "[...]/Aura-Text/auratext/Core/window.py", line 31, in <module>
    from . import get_started
ImportError: cannot import name 'get_started' from 'auratext.Core' ([...]/Aura-Text/auratext/Core/__init__.py)
```

## System Specs
 - Python version & OS: Python 3.11.6 on Ubuntu 23.10
 - Aura Text Version: git commit 4765ab2efc2e3f8977f769fc3568fc041ad81f3e

**Comment by rohankishore** [comment]
Hey @johnstanforth !

You can comment out the `get_started` file references since it will not interfere with the app's working. The file is made to show an interactive window when the user opens the app for the first time. I've updated the repo anyway. 

As for the Linux support, you can use any other corresponding libraries instead of win32 to get the output. I've planned to add a feature where it'll automatically recognize the OS and then use the corresponding libraries. 

Thank you for trying out Aura Text.

**Comment by johnstanforth** [comment]
Thanks @rohankishore !  I should have mentioned that I already commented that out to get the IDE launched, but didn't want to create a Pull Request to change it since I was still looking into the win32 dependencies. :-)  But yes, commenting that out works and thanks for fixing in the repo.  Looking forward to seeing your progress on this project.

**Comment by rohankishore** [comment]
You're welcome! And yes, a lot of new stuff are coming soon ;)
