### ISSUE TITLE
Asking for exit confirmation even though there are no open files/tabs

### ISSUE THREAD

**Issue by rohankishore** [rohankishore/Aura-Text#77]

**Comment by itszux** [comment]
It still appear

**Comment by rohankishore** [comment]
did you try it with new commit? Coz its working for me

**Comment by itszux** [comment]
my bad, I was using the latest release not the latest commit

**Comment by rohankishore** [comment]
oh ok understandable. Have a nice day!

**Comment by itszux** [comment]
You too.
I submitted another issue and I don't know if it's fixed in later commit also, but I can't reproduce it since I already installed the modules globally

**Comment by rohankishore** [comment]
Yeah thanks for reporting those issues. I've fixed it now. Thanks a lot once again. I'll be making a new release with the current code so it'll be easier to roll back.
