### ISSUE TITLE
modules missing [BUG]

### ISSUE THREAD

**Issue by itszux** [rohankishore/Aura-Text#78]
# Bug

## Describe the bug
Even after installing the requirements file, some modules still not found
1- pyqt_find_replace_text_widget
2- pywinstyles
3- absresgetter
4- roastedbyai

**Comment by rohankishore** [comment]
Oh yeah my bad I haven't updated the requirements.txt file. In the meantime you can install the following packages via pip.

```bash
pip install pyqt-find-replace-text-widget
```

```bash
pip install pywinstyles
```

```bash
pip install absresgetter
```

```bash
pip install pip install roastedbyai
```
