### ISSUE TITLE
compiling

### ISSUE THREAD

**Issue by not-nef** [rohankishore/Aura-Text#8]
damn how do you compile this thing the archive is so full

**Comment by rohankishore** [comment]
Like what do you mean? How to run this or convert it to an exe? And btw, in the next version, it'll be much better... I dumped the Azure theme for Customtkinter. So, the  ` theme` folder and `theme.tcl` file will not be present. Also, the file `cmdlist.png` will also not be there. But as of the current stage (v1.0.7), yeah there will be these folders and hell lot of files present in them...

Thanks for showing interest in Aura Notes.

**Comment by rohankishore** [comment]
For info about compiling, check the wiki post here:

[https://github.com/rohankishore/Aura-Notes/wiki/Setting-Up-(Developers)](https://github.com/rohankishore/Aura-Notes/wiki/Setting-Up-(Developers))

Thanks! This issue will be closed as you haven't replied till now. If you face any more problem, feel free to open another issue.
