### ISSUE TITLE
License Conflict: MIT License with PyQt6 (GPLv3)

### ISSUE THREAD

**Issue by kun-codes** [rohankishore/Aura-Text#95]
Hi, 

this isn't a bug report but I noticed that you have licensed this project with MIT license. PyQt6 is licensed under GPLv3 which isn't compatible with MIT. I suggest you switch to GPLv3 for this project after talking to every contributor till now since they hold a copyright over the code they contributed. You can choose to rewrite the code which has been contributed by someone else in case you aren't able to reach out to them or they don't agree to the change in license.

**Comment by rohankishore** [comment]
Hey @kun-codes!

Thank you for pointing this issue out. I've changed the license to GPLv3. Once again, 

Thanks
Rohan Kishore

**Comment by kun-codes** [comment]
I suggest you change licenses on your other pyqt6 projects too. By the way, did you ask the consent of other contributors before changing the license?

**Comment by rohankishore** [comment]
How can I ask consent of other contributors? And yes, I'll update other projects too
